
const db=window.VGIK_DB||{}, allItems=Array.isArray(db.items)?db.items:[], idMap=new Map(allItems.map(q=>[q.id,q]));
const $=id=>document.getElementById(id), KEY="vgik-test-v17";
const THEMES=[["all","Все"],["physics","Физика"],["creativeFolder","Творческая папка"],["sovietCinema","Кино СССР/РФ"],["frenchCinema","Кино Франция"],["festivalCinema","Фестивальное кино"],["sound","Звукорежиссура"],["directors","Режиссёры"],["philosophy","Философия кино"]];
const CONTENTS={all:[["all","Всё"],["films","Все фильмы"],["terms","Термины"],["tasks","Задачи"],["examples","Примеры сцен"]],physics:[["all","Вся физика"],["формулы и законы","Формулы и законы"],["задачи с числами","Задачи с числами"],["звук и волны","Звук и волны"],["электрические цепи","Электрические цепи"],["электростатика","Электростатика"],["конденсаторы и фильтры","Конденсаторы"],["магнитное поле","Магнитное поле"],["индукция и трансформатор","Индукция"],["механика и колебания","Механика"],["радио и электромагнитные волны","Радио"],["единицы и величины","Единицы"]],creativeFolder:[["all","Вся папка"],["автобиография","Автобиография"],["экранная версия","Экранная версия"],["звукозрительный анализ","Звукозрительный анализ"],["термины","Термины"],["общие вопросы по папке","Общие вопросы"]],sovietCinema:[["all","Всё СССР/РФ"],["Тарковский","Тарковский"],["Рязанов","Рязанов"],["Эйзенштейн","Эйзенштейн"],["советская авторская классика","Авторская классика"],["новое российское кино","Новое российское"],["кино СССР/РФ","Общее"]],frenchCinema:[["all","Вся Франция"],["новая волна","Новая волна"],["звук у Тати/Брессона","Тати/Брессон"],["музыка и звук Франции","Музыка и звук"],["французское авторское кино","Авторское кино"]],festivalCinema:[["all","Все фестивали"],["Канны","Канны"],["Венеция","Венеция"],["Берлин","Берлин"],["1950-е","1950-е"],["1960-е","1960-е"],["1970-е","1970-е"],["1980-е","1980-е"],["1990-е","1990-е"]],sound:[["all","Вся звукорежиссура"],["музыка","Музыка"],["голос и речь","Голос и речь"],["шумы и фонограмма","Шумы"],["монтаж и пространство","Монтаж/пространство"],["термины","Термины"]],directors:[["all","Все режиссёры"],["Тарковский","Тарковский"],["Рязанов","Рязанов"],["Годар","Годар"],["Тати","Тати"],["Феллини","Феллини"],["Антониони","Антониони"]],philosophy:[["all","Вся философия"],["память и внутреннее состояние","Память/состояние"],["страх и давление среды","Страх/среда"],["авторский комментарий","Авторский комментарий"],["реализм и условность","Реализм/условность"],["философия кино","Общее"]]};
let state={theme:"all",content:"all",director:"all",country:"all",festival:"all",decade:"all",search:"",current:null,locked:false,total:0,correct:0,streak:0,progress:{},errorQueue:[],recentIds:[],sessionSeenIds:[],settings:{onlyWrong:false,hardMode:false}};
try{const s=JSON.parse(localStorage.getItem(KEY)||"{}");state={...state,...s,settings:{...state.settings,...(s.settings||{})}}}catch(e){}
function save(){localStorage.setItem(KEY,JSON.stringify(state))} function cat(q){return q.category||"sound"} function label(t){return (THEMES.find(x=>x[0]===t)||[0,"Все"])[1]}
function qtext(q){return [q.question,q.answer,q.full_answer,q.explanation,q.topic_name,(q.tags||[]).join(" "),q.director,q.country,q.festival,q.decade,q.content_group,q.physics_group].filter(Boolean).join(" ").toLowerCase().replaceAll("ё","е")}
function progress(id){return state.progress[id]=state.progress[id]||{correct:0,wrong:0,last:0}}
function matchesTheme(q){return state.theme==="all"||cat(q)===state.theme}
function matchesContent(q){if(state.content==="all")return true;const s=qtext(q), cg=(q.content_group||q.physics_group||"").toLowerCase();if(state.theme==="all"){if(state.content==="films")return ["sovietCinema","frenchCinema","festivalCinema"].includes(cat(q))||q.director||q.year;if(state.content==="terms")return /термин|тембр|лейтмотив|контрапункт|синхрон/.test(s);if(state.content==="tasks")return /задача|дано|найди/.test(s)||cat(q)==="physics";if(state.content==="examples")return /сцена|пример|фильм/.test(s)} return cg===state.content.toLowerCase()||s.includes(state.content.toLowerCase())||q.festival===state.content||q.decade===state.content}
function matchesSmart(q){if(state.director!=="all"&&(q.director||"")!==state.director)return false;if(state.country!=="all"&&(q.country||"")!==state.country)return false;if(state.festival!=="all"&&(q.festival||"")!==state.festival)return false;if(state.decade!=="all"&&(q.decade||"")!==state.decade)return false;if(state.search.trim()){const s=qtext(q), terms=state.search.toLowerCase().replaceAll("ё","е").split(/\s+/).filter(Boolean);if(!terms.every(t=>s.includes(t)))return false}return true}
function pool(){let p=allItems.filter(q=>matchesTheme(q)&&matchesContent(q)&&matchesSmart(q));if(state.settings.onlyWrong)p=p.filter(q=>{const r=state.progress[q.id];return r&&r.wrong>r.correct});return p.length?p:allItems.filter(matchesTheme)}
function recentGroups(n){const out=[];for(const id of state.recentIds){const q=idMap.get(id);if(q){out.push(cat(q)==="physics"?(q.physics_group||q.content_group):(q.content_group||cat(q)));if(out.length>=n)break}}return out}
function variety(list){if(list.length<2)return list;const recent=recentGroups(state.theme==="physics"?5:3);const f=list.filter(q=>!recent.includes(cat(q)==="physics"?(q.physics_group||q.content_group):(q.content_group||cat(q))));return f.length?f:list}
function noRepeat(list,d=18){const r=new Set(state.recentIds.slice(0,d));return list.filter(q=>!r.has(q.id))}
function pick(list){list=variety(list);return list.map(q=>{const r=progress(q.id);let sc=Math.random()*4+(q.difficulty||3)+(state.settings.hardMode?(q.difficulty||0):0)+(r.wrong>r.correct?2:0)-(state.sessionSeenIds.includes(q.id)?3:0);return[sc,q]}).sort((a,b)=>b[0]-a[0])[0]?.[1]||list[0]}
function nextQ(){let p=pool();let due=state.errorQueue.filter(e=>e.dueAt<=state.total).map(e=>idMap.get(e.id)).filter(q=>q&&p.includes(q));due=noRepeat(due,6);if(due.length)return pick(due);let fresh=noRepeat(p,18);if(!fresh.length)fresh=noRepeat(p,8);return pick(fresh.length?fresh:p)}
function render(){const q=nextQ();state.current=q;state.locked=false;save();$("result").classList.add("hidden");$("nextBtn").classList.add("hidden");$("options").innerHTML="";if(!q){$("question").textContent="В этом фильтре нет вопросов. Ослабь фильтр.";meta();return}$("question").textContent=q.question;let ch=(Array.isArray(q.choices)&&q.choices.length?q.choices:[q.answer,"нет данных","другой вариант","общая формулировка"]).slice(0,6);ch.forEach((c,i)=>{const b=document.createElement("button");b.className="option";b.innerHTML=`<span class="letter">${"АБВГДЕ"[i]||i+1}</span><span>${c}</span>`;b.onclick=()=>ans(c,b);$("options").appendChild(b)});meta()}
function ans(choice,btn){if(state.locked||!state.current)return;state.locked=true;const q=state.current,c=String(q.answer||"").trim(),ok=String(choice).trim()===c;state.total++;if(ok){state.correct++;state.streak++}else{state.streak=0;state.errorQueue=state.errorQueue.filter(e=>e.id!==q.id);state.errorQueue.push({id:q.id,dueAt:state.total+5+Math.floor(Math.random()*6)})}const r=progress(q.id);ok?r.correct++:r.wrong++;r.last=Date.now();state.recentIds=[q.id,...state.recentIds.filter(id=>id!==q.id)].slice(0,90);state.sessionSeenIds=[q.id,...state.sessionSeenIds.filter(id=>id!==q.id)].slice(0,600);document.querySelectorAll(".option").forEach(o=>{const t=o.querySelector("span:last-child")?.textContent||"";if(t.trim()===c)o.classList.add("correct");if(o===btn&&!ok)o.classList.add("wrong")});$("resultMark").textContent=ok?"верно":"ошибка";$("correctAnswer").textContent=c;$("explanation").textContent=q.full_answer||q.explanation||"";$("result").classList.remove("hidden");$("nextBtn").classList.remove("hidden");save();meta()}
function meta(){const p=pool();let bits=[label(state.theme)];[state.content,state.director,state.country,state.festival,state.decade].forEach(x=>{if(x&&x!=="all")bits.push(x)});$("meta").textContent=`${bits.join(" / ")} · ${p.length} вопросов`;$("stats").textContent=`${state.correct}/${state.total} · серия ${state.streak}`}
function unique(a){return [...new Set(a.filter(Boolean))].sort((x,y)=>String(x).localeCompare(String(y),"ru"))}
function renderMenu(){const tb=$("themeButtons");tb.innerHTML="";THEMES.forEach(([k,l])=>{const b=document.createElement("button");b.textContent=l;if(state.theme===k)b.classList.add("active");b.onclick=()=>{state.theme=k;state.content="all";state.director=state.country=state.festival=state.decade="all";save();renderMenu();render()};tb.appendChild(b)});const cf=$("contentFilters");cf.innerHTML="";(CONTENTS[state.theme]||CONTENTS.all).forEach(([k,l])=>{const b=document.createElement("button");b.className="filter-chip";b.textContent=l;if(state.content===k)b.classList.add("active");b.onclick=()=>{state.content=k;state.director=state.country=state.festival=state.decade="all";save();renderMenu();render()};cf.appendChild(b)});smart();$("onlyWrong").checked=state.settings.onlyWrong;$("hardMode").checked=state.settings.hardMode;$("searchInput").value=state.search||"";meta()}
function universe(){return allItems.filter(q=>matchesTheme(q)&&matchesContent(q))}
function select(name,key,vals){const lab=document.createElement("label");lab.className="select-label";lab.textContent=name;const s=document.createElement("select");s.innerHTML='<option value="all">Все</option>'+vals.map(v=>`<option value="${String(v).replaceAll('"','&quot;')}">${v}</option>`).join("");s.value=state[key]||"all";s.onchange=()=>{state[key]=s.value;save();render();meta()};lab.appendChild(s);return lab}
function smart(){const box=$("smartFilters");box.innerHTML="";const u=universe();const show=["all","sovietCinema","frenchCinema","festivalCinema","directors","philosophy","sound"].includes(state.theme);if(!show)return;const dirs=unique(u.map(q=>q.director)),countries=unique(u.map(q=>q.country)),fests=unique(u.map(q=>q.festival)),decs=unique(u.map(q=>q.decade));if(dirs.length)box.appendChild(select("Режиссёр","director",dirs));if(countries.length)box.appendChild(select("Страна","country",countries));if(fests.length)box.appendChild(select("Фестиваль","festival",fests));if(decs.length)box.appendChild(select("Десятилетие","decade",decs))}
$("menuBtn").onclick=()=>{$("drawer").classList.remove("hidden");renderMenu()};$("closeDrawer").onclick=()=>$("drawer").classList.add("hidden");$("drawer").onclick=e=>{if(e.target.id==="drawer")$("drawer").classList.add("hidden")};$("nextBtn").onclick=render;$("onlyWrong").onchange=e=>{state.settings.onlyWrong=e.target.checked;save();render()};$("hardMode").onchange=e=>{state.settings.hardMode=e.target.checked;save();render()};$("resetBtn").onclick=()=>{if(confirm("Сбросить прогресс?")){localStorage.removeItem(KEY);location.reload()}};$("searchInput").oninput=e=>{state.search=e.target.value;save();render();meta()};renderMenu();render();if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js?v=17").catch(()=>{});
